coursesessions/api/urls.py
from django.conf.urls import url

from coursesessions.api.views import SessionListAPIView, SessionDetailAPIView

urlpatterns = [
    url(r'^$', SessionListAPIView.as_view(), name='session-list'),
    url(r'^(?P<pk>[0-9]+)/$', SessionDetailAPIView.as_view(), name='session-detail'),
]

coursesessions/urls.py
from django.conf.urls import url

from coursesessions.views import CourseSessionDetailView, CreateSessionView, IndexView

app_name = 'coursesessions'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', CourseSessionDetailView.as_view(), name='detail'),
    url(r'^create_session/$', CreateSessionView.as_view(), name='create_session'),
]

polls/urls.py
from django.conf.urls import url

from polls.views import CreatePollView, IndexView, PollDetailView, ResultsView

app_name = 'polls'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/(?P<session_id>[0-9]+)/$', PollDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', ResultsView.as_view(), name='results'),
    url(r'^create_poll/(?P<session_id>[0-9]+)/$', CreatePollView.as_view(), name='create_poll'),
]

thesis/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include('homepage.urls')),
    url(r'^coursesessions/', include('coursesessions.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^api/polls/', include('polls.api.urls')),
    url(r'^api/sessions/', include('coursesessions.api.urls')),
]

urlpatterns += staticfiles_urlpatterns()

coursesessions/models.py
from django.contrib.auth.models import User
from django.db import models


class CourseSession(models.Model):
    session_name = models.CharField(max_length=200)
    admins = models.ManyToManyField(User, related_name='admins')
    participants = models.ManyToManyField(User, related_name='participants')

    def __str__(self):
        return self.session_name

    class Meta:
        permissions = (
            ('make_poll', 'Make Poll'),
        )

coursesessions/api/views.py
from rest_framework.generics import ListAPIView, RetrieveAPIView

from coursesessions.models import CourseSession
from .serializers import SessionSerializer


class SessionListAPIView(ListAPIView):
    queryset = CourseSession.objects.all()
    serializer_class = SessionSerializer


class SessionDetailAPIView(RetrieveAPIView):
    queryset = CourseSession.objects.all()
    serializer_class = SessionSerializer

coursesessions/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from guardian.shortcuts import assign_perm
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template import loader
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DetailView

from coursesessions.models import CourseSession


class IndexView(View):
    def get(self, request):
        sessions = CourseSession.objects.all()
        template = loader.get_template('coursesessions/index.html')
        context = {
            'sessions': sessions,
        }
        return HttpResponse(template.render(context, request))


class CreateSessionView(View):
    template = "coursesessions/create_session.html"

    @method_decorator(login_required)
    def post(self, request):
        session_name = request.POST['session_name']
        new_session = CourseSession(session_name=session_name)
        new_session.save()
        init_admin = User.objects.get(pk=request.user.id)
        new_session.admins = [init_admin]
        assign_perm('make_poll', init_admin, new_session)
        new_session.save()

        return HttpResponseRedirect(reverse('coursesessions:detail', args=(new_session.id,)))

    def get(self, request):
        return render(request, self.template)


class CourseSessionDetailView(DetailView):
    template_name = "coursesessions/detail.html"

    def get_context_data(self, **kwargs):
        context = super(CourseSessionDetailView, self).get_context_data(**kwargs)
        session = CourseSession.objects.get(pk=self.kwargs['pk'])
        context['session'] = session
        context['questions'] = session.question_set.all()
        return context

    model = CourseSession

coursesessions/templates/coursesessions/create_session.html
{% extends 'homepage/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>Create a new Session</h1>
            <form id="pollForm" method="post" class="form-horizontal">
                {% csrf_token %}

                    <div class="form-group">
                        <label class="col-xs-3 control-label" for="session_name">Session Name</label>
                        <div class="col-xs-5">
                            <input type="text" class="form-control" name="session_name" id="session_name"/>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-xs-3 control-label" for="session">Creator:</label>
                        <p>{{ request.user }}</p>
                        <div class="col-xs-5">
                            <input type="hidden" name="session" value="{{ request.user.id }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-5 col-xs-offset-3">
                            <button type="submit" class="btn btn-default">New Session</button>
                        </div>
                    </div>
            </form>


        </div>
    </div>
{% endblock %}

coursesessions/templates/coursesessions/detail.html
{% extends 'homepage/base.html' %}
{% load guardian_tags %}
{% block content %}
    {% get_obj_perms request.user for session as "session_perms" %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>Session Name: {{ session }}</h1>
            <p><strong>Admin: {{ session.admins.all.0 }}</strong></p>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% if questions %}
            <h2>Polls:</h2>
            {% for question in questions %}
                <h3><a href="../../polls/{{ question.pk }}/{{ session.id }}">{{ question }}</a></h3>
            {% endfor %}
        {% else %}
            <h3>No Polls in this Session yet</h3>
        {% endif %}
        {% if "make_poll" in session_perms %}
            <br />
            <a href="{% url 'polls:create_poll' session_id=session.id %}" class="btn btn-primary">New Poll</a>
        {% endif %}
        </div>
    </div>
{% endblock %}

coursesessions/templates/coursesessions/index.html
{% extends 'homepage/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>All Sessions:</h1>
            <div>
                {% if sessions %}
                    {% for session in sessions %}
                        <h2><a href="{{ session.pk }}">{{ session }}</a></h2>
                    {% endfor %}
                {% endif %}
                {% if request.user.is_authenticated %}
                    <a href="{% url 'coursesessions:create_session' %}" class="btn btn-primary">New Session</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}