coursesessions/urls.py
from django.conf.urls import url

from coursesessions.views import CourseSessionDetailView, CreateSessionView, IndexView

app_name = 'coursesessions'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', CourseSessionDetailView.as_view(), name='detail'),
    url(r'^create_session/$', CreateSessionView.as_view(), name='create_session'),
]

homepage/urls.py
from django.conf.urls import url

from . import views

app_name = 'homepage'
urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
]

polls/urls.py
from django.conf.urls import url

from polls.views import CreatePollView, IndexView, PollDetailView, ResultsView

app_name = 'polls'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/(?P<session_id>[0-9]+)/$', PollDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', ResultsView.as_view(), name='results'),
    url(r'^create_poll/(?P<session_id>[0-9]+)/$', CreatePollView.as_view(), name='create_poll'),
]

thesis/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include('homepage.urls')),
    url(r'^coursesessions/', include('coursesessions.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^api/polls/', include('polls.api.urls')),
    url(r'^api/sessions/', include('coursesessions.api.urls')),
]

urlpatterns += staticfiles_urlpatterns()

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.http import HttpResponse
from django.template import loader


def homepage(request):
    template = loader.get_template('homepage/homepage.html')
    return HttpResponse(template.render({}, request))

homepage/templates/homepage/base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Thesis</title>

    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <script type="text/javascript" src={% static 'global_js/jquery-3.1.1.min.js' %}></script>
    <script type="text/javascript" src={% static 'bootstrap/js/bootstrap.min.js' %}></script>
    <script type="text/javascript" src={% static 'js/dynamic_field.js' %}></script>
</head>
<body>
    <div id="header">
    {% block header %}
    <a href="{% url 'homepage:homepage' %}">{% trans "Home" %}</a> |

    {% if user.is_authenticated %}
        {% trans "Logged in" %}: {{ user.username }}
        (<a href="{% url 'auth_logout' %}">{% trans "Log out" %}</a> |
        <a href="{% url 'auth_password_change' %}">{% trans "Change password" %}</a>)
    {% else %}
       <a href="{% url 'auth_login' %}">{% trans "Log in" %}</a>
       <a href="/accounts/register">{% trans "Register" %}</a>
    {% endif %}
    <hr />
    {% endblock %}
    </div>

    <div id="content">
    {% block content %}{% endblock %}
    </div>

    <div id="footer">
    {% block footer %}
        <hr />
    {% endblock %}
    </div>
</body>
</html>

homepage/templates/homepage/homepage.html
{% extends 'homepage/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>Go to Sessions:</h1>
            <div>
                <h2><a href={% url 'coursesessions:index' %}>Sessions</a></h2>
            </div>
        </div>
    </div>
{% endblock %}