coursesessions/urls.py
from django.conf.urls import url

from coursesessions.views import CourseSessionDetailView, CreateSessionView, IndexView

app_name = 'coursesessions'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', CourseSessionDetailView.as_view(), name='detail'),
    url(r'^create_session/$', CreateSessionView.as_view(), name='create_session'),
]

polls/api/urls.py
from django.conf.urls import url

from polls.api.views import PollListAPIView, PollDetailAPIView

urlpatterns = [
    url(r'^$', PollListAPIView.as_view(), name='poll-list'),
    url(r'^(?P<pk>[0-9]+)/$', PollDetailAPIView.as_view(), name='poll-detail'),
]

polls/urls.py
from django.conf.urls import url

from polls.views import CreatePollView, IndexView, PollDetailView, ResultsView

app_name = 'polls'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/(?P<session_id>[0-9]+)/$', PollDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', ResultsView.as_view(), name='results'),
    url(r'^create_poll/(?P<session_id>[0-9]+)/$', CreatePollView.as_view(), name='create_poll'),
]

thesis/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include('homepage.urls')),
    url(r'^coursesessions/', include('coursesessions.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^api/polls/', include('polls.api.urls')),
    url(r'^api/sessions/', include('coursesessions.api.urls')),
]

urlpatterns += staticfiles_urlpatterns()

polls/models.py
from django.db import models

from coursesessions.models import CourseSession


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    session = models.ForeignKey(CourseSession, on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.question_text


class Option(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=False)
    option_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.option_text

polls/api/views.py
from rest_framework.generics import ListAPIView, RetrieveAPIView

from polls.models import Question
from .serializers import PollSerializer


class PollListAPIView(ListAPIView):
    queryset = Question.objects.all()
    serializer_class = PollSerializer


class PollDetailAPIView(RetrieveAPIView):
    queryset = Question.objects.all()
    serializer_class = PollSerializer

polls/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template import loader
from django.utils.decorators import method_decorator
from django.utils.timezone import now
from django.views import View
from django.views.generic import DetailView
from guardian.shortcuts import get_perms

from coursesessions.models import CourseSession
from polls.models import Question, Option


class IndexView(View):
    def get(self, request):
        return HttpResponseRedirect(reverse('coursesessions:index'))


class CreatePollView(View):
    template = "polls/create_poll.html"

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        session = CourseSession.objects.get(pk=self.kwargs['session_id'])
        if "make_poll" in get_perms(request.user, session):
            question_text = request.POST['question']
            new_question = Question(question_text=question_text, pub_date=now(), session=session)
            new_question.save()

            options_list = request.POST.getlist('options')
            for option in options_list:
                option_text = option
                new_option = Option(option_text=option_text, question=new_question)
                new_option.save()

            return HttpResponseRedirect(reverse('polls:detail', args=(new_question.id, session.id)))
        else:
            return render(request, 'coursesessions/detail.html', {
                'session': session,
                'error_message': "You are not an admin for this Session.",
            })

    def get(self, request, *args, **kwargs):
        context = {'session': CourseSession.objects.get(pk=self.kwargs['session_id'])}
        return render(request, self.template, context=context)


class PollDetailView(DetailView):
    template_name = "polls/detail.html"

    def get_context_data(self, **kwargs):
        context = super(PollDetailView, self).get_context_data(**kwargs)
        question = Question.objects.get(pk=self.kwargs['pk'])
        context['options'] = question.option_set.all().order_by('pk')
        return context

    def post(self, request, *args, **kwargs):
        question = Question.objects.get(pk=self.kwargs['pk'])
        options = question.option_set.all().order_by('pk')
        try:
            selected_choice = question.option_set.get(pk=request.POST['option'])
        except (KeyError, Option.DoesNotExist):
            return render(request, 'polls/detail.html', {
                'question': question,
                'options': options,
                'error_message': "You didn't select an option.",
            })
        else:
            selected_choice.votes += 1
            selected_choice.save()
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

    model = Question


class ResultsView(DetailView):
    template_name = "polls/results.html"

    def get_context_data(self, **kwargs):
        context = super(ResultsView, self).get_context_data(**kwargs)
        question = Question.objects.get(pk=self.kwargs['pk'])
        context['options'] = question.option_set.all().order_by('pk')
        return context

    model = Question

polls/templates/polls/create_poll.html
{% extends 'homepage/base.html' %}
{% block content %}
    <script type="text/html" id="optionTemplate">
        <div class="form-group">
            <label class="col-xs-3 control-label"></label>
            <div class="col-xs-5">
                <input class="form-control option" type="text" name="options" required/>
            </div>
            <div class="col-xs-4">
                <button type="button" class="btn btn-default removeButton"><span
                        class="glyphicon glyphicon-minus"></span></button>
            </div>
        </div>
    </script>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>New Poll</h1>
            <form id="pollForm" method="post" class="form-horizontal">
                {% csrf_token %}

                <div class="form-group">
                    <label class="col-xs-3 control-label" for="session">Session:</label>
                    <p>{{ session }}</p>
                    <div class="col-xs-5">
                        <input type="hidden" name="session" value="{{ session.id }}">
                    </div>
                </div>

                    <div class="form-group">
                        <label class="col-xs-3 control-label" for="question">Question</label>
                        <div class="col-xs-5">
                            <input type="text" class="form-control" name="question" id="question" required/>
                        </div>
                    </div>

                    <div class="options">
                        <div class="form-group">
                            <label class="col-xs-3 control-label" for="option1">Options</label>
                            <div class="col-xs-5">
                                <input type="text" class="form-control option" id="option1" name="options" required/>
                            </div>
                            <div class="col-xs-4">
                                <button type="button" class="btn btn-default addButton"><span
                                        class="glyphicon glyphicon-plus"></span></button>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-5 col-xs-offset-3">
                            <button type="submit" class="btn btn-default">New Poll</button>
                        </div>
                    </div>
            </form>


        </div>
    </div>
{% endblock %}

polls/templates/polls/detail.html
{% extends 'homepage/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>{{ question.question_text }}</h1>

            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

            <form action="." method="post">
                {% csrf_token %}
                {% for option in options %}
                    <p>
                        <input type="radio" name="option" id="option{{ forloop.counter }}" value="{{ option.id }}"/>
                        <label for="option{{ forloop.counter }}">{{ option.option_text }}</label>
                    </p>
                {% endfor %}
                <div class="form-group">
                    <div class="col-xs-5 col-xs-offset-3">
                        <button type="submit" class="btn btn-default">Vote</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

polls/templates/polls/new_poll.html
{% extends 'polls/base.html' %}
{% block content %}
    <script type="text/html" id="optionTemplate">
        <div class="form-group">
            <label class="col-xs-3 control-label"></label>
            <div class="col-xs-5">
                <input class="form-control option" type="text" name="options"/>
            </div>
            <div class="col-xs-4">
                <button type="button" class="btn btn-default removeButton"><span class="glyphicon glyphicon-minus"></span></button>
            </div>
        </div>
    </script>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>New Poll</h1>
            <h2>{{ user }}</h2>
            <a href="{% url 'auth_logout' %}">"Log out"</a>
            <form id="pollForm" method="post" class="form-horizontal">
                {% csrf_token %}
                <div class="form-group">
                    <label class="col-xs-3 control-label">Question</label>
                    <div class="col-xs-5">
                        <input type="text" class="form-control" name="question"/>
                    </div>
                </div>

                <div class="options">
                    <div class="form-group">
                        <label class="col-xs-3 control-label" for="option1">Options</label>
                        <div class="col-xs-5">
                            <input type="text" class="form-control option" id="option1" name="options"/>
                        </div>
                        <div class="col-xs-4">
                            <button type="button" class="btn btn-default addButton"><span class="glyphicon glyphicon-plus"></span></button>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-5 col-xs-offset-3">
                        <button type="submit" class="btn btn-default">New Poll</button>
                    </div>
                </div>
            </form>


        </div>
    </div>
{% endblock %}

polls/templates/polls/results.html
{% extends 'homepage/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>{{ question.question_text }}</h1>

            <ul>
                {% for option in options %}
                    <li><strong>{{ option.option_text }}</strong>: {{ option.votes }} vote{{ option.votes|pluralize }}</li>
                {% endfor %}
            </ul>

            <a href="{% url 'coursesessions:detail' pk=question.session.id %}" class="btn btn-default">Back to Home</a>
        </div>
    </div>
{% endblock %}